### ISSUE TITLE
TeX Live Utility upgrade problems

### ISSUE THREAD

**Issue by marcoxa** [amaxwell/tlutility#13]
Hi

I am running in a problem with TeX Live Utility on Yosemite.  This is the log.  Note that I have a fresh installation of MacTex and I cannot find 'kpsewhich' on my disk.

For what it's worth here's my PATH

Spanakorizo:~ marcoxa$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin

Any suggestions?

Thanks

MA

===============
Log starts here

.....
2015-02-23 12:30:53 +0000 Notice -[TLMMainWindowController _handleListUpdatesFinishedNotification:][411]	Critical updates detected: (
    "texlive.infra"
)
2015-02-23 12:30:55 +0000 Notice -[TLMMainWindowController _isCorrectDatabaseVersionAtURL:][411]	Checking database version in case preferences have been changed…
2015-02-23 12:30:55 +0000 Notice -[TLMMainWindowController _updateAllPackagesFromRepository:][411]	Beginning infrastructure update from http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet/
2015-02-23 12:30:55 +0000 Notice -[TLMInfraUpdateOperation _synchronouslyDownloadURL:toPath:][411]	Downloading URL: http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh
2015-02-23 12:30:55 +0000 Notice -[TLMInfraUpdateOperation download:willSendRequest:redirectResponse:][411]	Download redirected to http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh, expecting 0 bytes.
2015-02-23 12:30:55 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveResponse:][411]	Will download 4794150 bytes…
2015-02-23 12:30:55 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][411]	Received 20% of 4794150 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][411]	Received 41% of 4794150 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][411]	Received 61% of 4794150 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][411]	Received 82% of 4794150 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation downloadDidFinish:][411]	Download of 4794150 bytes complete
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation _downloadUpdateScript][411]	First line of downloaded file is: "#!/bin/sh"…good!
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation _synchronouslyDownloadURL:toPath:][411]	Downloading URL: http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh.sha256
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:willSendRequest:redirectResponse:][411]	Download redirected to http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh.sha256, expecting 0 bytes.
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveResponse:][411]	Will download 89 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][411]	Received 100% of 89 bytes…
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation downloadDidFinish:][411]	Download of 89 bytes complete
2015-02-23 12:30:56 +0000 Notice -[TLMInfraUpdateOperation _downloadAndCheckHash][411]	SHA256 signature looks okay
2015-02-23 12:30:56 +0000 Notice -[TLMAuthorizedOperation main][411]	Checking code signature before running tlu_ipctask as root…
2015-02-23 12:30:56 +0000 Notice /usr/bin/codesign[411]	/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: valid on disk
/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: satisfies its Designated Requirement
2015-02-23 12:30:56 +0000 Notice -[TLMAuthorizedOperation main][411]	Signature was valid, okay to run tlu_ipctask
2015-02-23 12:31:00 +0000 Notice -[TLMAuthorizedOperation main][411]	Invoking privileged task via AuthorizationExecuteWithPrivileges
2015-02-23 12:31:00 +0000 Notice tlu_ipctask[536]	dropped privileges to user nobody
2015-02-23 12:31:01 +0000 Notice -[TLMAuthorizedOperation setWrapperPID:][411]	tlu_ipctask checking in:  tlu_ipctask pid = 536
2015-02-23 12:31:02 +0000 Notice -[TLMAuthorizedOperation setUnderlyingPID:][411]	tlu_ipctask checking in: pid = 537 (/var/folders/l4/b71hhwhj3f375fqgpw1r_f8c0000gp/T/TLMInfraUpdateOperation.jItWc3/update-tlmgr-latest.sh --nox11)
2015-02-23 12:31:02 +0000 Notice tlu_ipctask[536]	tlu_ipctask: child HOME = '/var/root'
2015-02-23 12:31:02 +0000 Notice tlu_ipctask[536]	tlu_ipctask: current HOME = '/var/empty'
2015-02-23 12:31:02 +0000 Notice tlu_ipctask[536]	Verifying archive integrity... All good.
2015-02-23 12:31:02 +0000 Notice tlu_ipctask[536]	Uncompressing TeX Live Manager Updater......................................................................................................................................................................................
2015-02-23 12:31:02 +0000 Warning tlu_ipctask[536]	./runme.sh: line 11: kpsewhich: command not found
2015-02-23 12:31:02 +0000 Warning tlu_ipctask[536]	./runme.sh: Cannot find TeX Live root using kpsewhich --var-value=SELFAUTOPARENT.
2015-02-23 12:31:02 +0000 Warning tlu_ipctask[536]	./runme.sh: Please set your PATH as needed, otherwise it's hopeless.
2015-02-23 12:31:02 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][411]	kqueue noted that pid 537 exited (/var/folders/l4/b71hhwhj3f375fqgpw1r_f8c0000gp/T/TLMInfraUpdateOperation.jItWc3/update-tlmgr-latest.sh --nox11)
2015-02-23 12:31:02 +0000 Notice tlu_ipctask[536]	child process pid = 537 exited
2015-02-23 12:31:03 +0000 Error tlu_ipctask[536]	Value of errno is No such file or directory
2015-02-23 12:31:03 +0000 Error tlu_ipctask[536]	*** ERROR *** exit status of pid = 537 was 1
2015-02-23 12:31:03 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][411]	waitpid returned 536, WIFEXITED(256) = 1, errno = 93 (Attribute not found)
2015-02-23 12:31:03 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][411]	kqueue noted that tlu_ipctask (pid = 536) exited with status 1
2015-02-23 12:31:03 +0000 Notice -[TLMInfraUpdateOperation main][411]	Removed temp directory "/var/folders/l4/b71hhwhj3f375fqgpw1r_f8c0000gp/T/TLMInfraUpdateOperation.jItWc3"

**Comment by amaxwell** [comment]
Your mirror has a stale (buggy) version of update-tlmgr.sh and possibly TeX Live, as well; this problem was fixed over a month ago, I believe. Switch to another mirror/repository, and choose "Reinstall TeX Live Manager" from the Actions menu.

**Comment by marcoxa** [comment]
Thanks for the reply.

Can you point me to a working mirror?  I tried different mirrors in Italy,
Germany and Switzerland.

The result is always the same.  Cannot reinstall and the 'kpsewhich'
problem persists.

Thanks



On Mon, Feb 23, 2015 at 3:35 PM, amaxwell <notifications@github.com> wrote:

> Your mirror has a stale (buggy) version of update-tlmgr.sh and possibly
> TeX Live, as well; this problem was fixed over a month ago, I believe.
> Switch to another mirror/repository, and choose "Reinstall TeX Live
> Manager" from the Actions menu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75550533>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by amaxwell** [comment]
I just used http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet successfully.

**Comment by marcoxa** [comment]
Hi

I used the mirror you suggested but nothing worked from the GUI.  I had to
manually run

tlmgr update --self

and I was able to figure this out only thanks to the log.

Now TLU is happily upgrading my packages.

Thank you

Marco


On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com> wrote:

> I just used
> http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> successfully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by amaxwell** [comment]
If that's the case, I'd guess that you didn't execute the command I told you to in my initial response: you have to run "Reinstall TeX Live Manager" first from a good mirror.

On Feb 23, 2015, at 08:32 AM, Marco Antoniotti <notifications@github.com> wrote:

Hi

I used the mirror you suggested but nothing worked from the GUI. I had to
manually run

tlmgr update --self

and I was able to figure this out only thanks to the log.

Now TLU is happily upgrading my packages.

Thank you

Marco


On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com> wrote:

> I just used
> http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> successfully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by marcoxa** [comment]
Hi

I did run the Reinstall.  It just ended up with the same error.  What fixed
things was running the command line command.

Go figure :O

MA


On Mon, Feb 23, 2015 at 5:38 PM, amaxwell <notifications@github.com> wrote:

> If that's the case, I'd guess that you didn't execute the command I told
> you to in my initial response: you have to run "Reinstall TeX Live Manager"
> first from a good mirror.
>
> On Feb 23, 2015, at 08:32 AM, Marco Antoniotti <notifications@github.com>
> wrote:
>
> Hi
>
> I used the mirror you suggested but nothing worked from the GUI. I had to
> manually run
>
> tlmgr update --self
>
> and I was able to figure this out only thanks to the log.
>
> Now TLU is happily upgrading my packages.
>
> Thank you
>
> Marco
>
>
> On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com>
> wrote:
>
> > I just used
> > http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> > successfully.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558>.
> >
>
>
>
> --
> Marco Antoniotti
> Somewhere over the Rainbow
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75578623>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by amaxwell** [comment]
Very strange! Could you send me the full log from that failure? Email amaxwell AT mac DOT com. I tried it myself before posting, just to make sure the TL wasn't broken again, and had no problem. I'd like to fix anything that might have messed this up for you, though.

On Feb 23, 2015, at 12:00 PM, Marco Antoniotti <notifications@github.com> wrote:

Hi

I did run the Reinstall. It just ended up with the same error. What fixed
things was running the command line command.

Go figure :O

MA


On Mon, Feb 23, 2015 at 5:38 PM, amaxwell <notifications@github.com> wrote:

> If that's the case, I'd guess that you didn't execute the command I told
> you to in my initial response: you have to run "Reinstall TeX Live Manager"
> first from a good mirror.
>
> On Feb 23, 2015, at 08:32 AM, Marco Antoniotti <notifications@github.com>
> wrote:
>
> Hi
>
> I used the mirror you suggested but nothing worked from the GUI. I had to
> manually run
>
> tlmgr update --self
>
> and I was able to figure this out only thanks to the log.
>
> Now TLU is happily upgrading my packages.
>
> Thank you
>
> Marco
>
>
> On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com>
> wrote:
>
> > I just used
> > http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> > successfully.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558>.
> >
>
>
>
> --
> Marco Antoniotti
> Somewhere over the Rainbow
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75578623>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by marcoxa** [comment]
I don't have the computer where I was doing the installation (left it in
the office doing a backup).  Tomorrow I will check whether the log is still
there, but I think it may have been lost.

The main difference I noticed (while trying to "Reinstall" from the
washington mirror) was the message with the indication to run the command
from the shell.  I am not sure, but at least I'd say that the versions on
the mirrors do in fact differ.

Be back tomorrow.

Cheers
--
MA


On Mon, Feb 23, 2015 at 9:11 PM, amaxwell <notifications@github.com> wrote:

> Very strange! Could you send me the full log from that failure? Email
> amaxwell AT mac DOT com. I tried it myself before posting, just to make
> sure the TL wasn't broken again, and had no problem. I'd like to fix
> anything that might have messed this up for you, though.
>
>
> On Feb 23, 2015, at 12:00 PM, Marco Antoniotti <notifications@github.com>
> wrote:
>
> Hi
>
> I did run the Reinstall. It just ended up with the same error. What fixed
> things was running the command line command.
>
> Go figure :O
>
> MA
>
>
> On Mon, Feb 23, 2015 at 5:38 PM, amaxwell <notifications@github.com>
> wrote:
>
> > If that's the case, I'd guess that you didn't execute the command I told
> > you to in my initial response: you have to run "Reinstall TeX Live
> Manager"
> > first from a good mirror.
> >
> > On Feb 23, 2015, at 08:32 AM, Marco Antoniotti <notifications@github.com
> >
> > wrote:
> >
> > Hi
> >
> > I used the mirror you suggested but nothing worked from the GUI. I had to
> > manually run
> >
> > tlmgr update --self
> >
> > and I was able to figure this out only thanks to the log.
> >
> > Now TLU is happily upgrading my packages.
> >
> > Thank you
> >
> > Marco
> >
> >
> > On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com>
> > wrote:
> >
> > > I just used
> > > http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> > > successfully.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558
> >.
> > >
> >
> >
> >
> > --
> > Marco Antoniotti
> > Somewhere over the Rainbow
> > —
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75578623>.
>
> >
>
>
>
> --
> Marco Antoniotti
> Somewhere over the Rainbow
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75621750>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow

**Comment by amaxwell** [comment]
TLU keeps the last 5 or so session logs by default; they should be listed by date in the left side source list of the log window. If not, no big deal.

On Feb 23, 2015, at 12:24 PM, Marco Antoniotti <notifications@github.com> wrote:

I don't have the computer where I was doing the installation (left it in
the office doing a backup). Tomorrow I will check whether the log is still
there, but I think it may have been lost.

The main difference I noticed (while trying to "Reinstall" from the
washington mirror) was the message with the indication to run the command
from the shell. I am not sure, but at least I'd say that the versions on
the mirrors do in fact differ.

Be back tomorrow.

Cheers
--
MA


On Mon, Feb 23, 2015 at 9:11 PM, amaxwell <notifications@github.com> wrote:

> Very strange! Could you send me the full log from that failure? Email
> amaxwell AT mac DOT com. I tried it myself before posting, just to make
> sure the TL wasn't broken again, and had no problem. I'd like to fix
> anything that might have messed this up for you, though.
>
>
> On Feb 23, 2015, at 12:00 PM, Marco Antoniotti <notifications@github.com>
> wrote:
>
> Hi
>
> I did run the Reinstall. It just ended up with the same error. What fixed
> things was running the command line command.
>
> Go figure :O
>
> MA
>
>
> On Mon, Feb 23, 2015 at 5:38 PM, amaxwell <notifications@github.com>
> wrote:
>
> > If that's the case, I'd guess that you didn't execute the command I told
> > you to in my initial response: you have to run "Reinstall TeX Live
> Manager"
> > first from a good mirror.
> >
> > On Feb 23, 2015, at 08:32 AM, Marco Antoniotti <notifications@github.com
> >
> > wrote:
> >
> > Hi
> >
> > I used the mirror you suggested but nothing worked from the GUI. I had to
> > manually run
> >
> > tlmgr update --self
> >
> > and I was able to figure this out only thanks to the log.
> >
> > Now TLU is happily upgrading my packages.
> >
> > Thank you
> >
> > Marco
> >
> >
> > On Mon, Feb 23, 2015 at 4:24 PM, amaxwell <notifications@github.com>
> > wrote:
> >
> > > I just used
> > > http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet
> > > successfully.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75563558
> >.
> > >
> >
> >
> >
> > --
> > Marco Antoniotti
> > Somewhere over the Rainbow
> > —
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75578623>.
>
> >
>
>
>
> --
> Marco Antoniotti
> Somewhere over the Rainbow
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amaxwell/tlutility/issues/13#issuecomment-75621750>.
>



-- 
Marco Antoniotti
Somewhere over the Rainbow
